# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"


  config.vm.provider "virtualbox" do |v|
    config.vm.provision "shell", path: "script.sh"
    config.vm.hostname = "nfss"
    config.vm.network "forwarded_port", guest: 80, host: 8080,
    auto_correct: true
    v.memory = 1024
    v.cpus = 2
  end

end
