# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"


  config.vm.provider "virtualbox" do |v|
#    config.vm.provision "shell", path: "script.sh"
    config.vm.hostname = "otushw7"
    v.memory = 1024
    v.cpus = 1
  end

end
